server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
      encoding: UTF-8
management:
  health:
    redis:
      enabled: false

agent:
  cache:
    enabled: true
  ai:
    api-key: ${DEEPSEEK_API_KEY:sk-6765c10f44324f1ca189d06a4bb8ebe8}
